export const userTypes = {
    SET_EMAIL_LOGIN: 'SET_EMAIL_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    FORGOT_EMAIL_FAIL: 'FORGOT_EMAIL_FAIL',
    FORGOT_EMAIL_SUCCESS: 'FORGOT_EMAIL_SUCCESS',
    SET_EMAIL_FORGOTPASSWORD: 'SET_EMAIL_FORGOTPASSWORD',
    RESET_FORGOT_PASSWORD: 'RESET_FORGOT_PASSWORD',
    VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCCESS',
    VERIFY_OTP_FAIL: 'VERIFY_OTP_FAIL',
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAIL: 'FORGOT_PASSWORD_FAIL',
    RESET_IS_LOGIN: 'RESET_IS_LOGIN'
}

export const homeTypes = {
    SET_CATEGORY_BOOK: 'SET_CATEGORY_BOOK',
    SET_PUBLISHSER: "SET_PUBLISHSER",
    SET_PAGE: 'SET_PAGE',
    SET_BOOK: 'SET_BOOK',
    SET_TOTAL_PAGE: 'SET_TOTAL_PAGE',
    SET_SORT_TYPE: 'SET_SORT_TYPE',
    SET_RANGE: 'SET_RANGE',
    SET_NAME_TITLE_ITEM: 'SET_NAME_TITLE_ITEM',
    RESET_BOOK: 'RESET_BOOK',
    SET_BRANCH_SEARCH_BOOK:'SET_BRANCH_SEARCH_BOOK', 
    SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
    SET_AUTHOR: 'SET_AUTHOR',
    SET_ID_BRANCH: 'SET_ID_BRANCH',
}

export const productTypes = {
    SET_PRODUCT_DETAIL: 'SET_PRODUCT_DETAIL',
    SET_NAME_CATEGORY: 'SET_NAME_CATEGORY',
    SET_NAME_PUBLICSHER: 'SET_NAME_PUBLICSHER',
    SET_BOOK_RELATED: 'SET_BOOK_RELATED',
    SET_COMMENT: 'SET_COMMENT',
    SET_NAME_AUTHOR: 'SET_NAME_AUTHOR',
    SET_PAGE: 'SET_PAGE',
    SET_TOTAL_PAGE: 'SET_TOTAL_PAGE',

}
export const profileTypes = {
    SET_AUTH_LOGIN_SUCCESS: 'SET_AUTH_LOGIN_SUCCESS',
    SET_AUTH_LOGIN_FAIL: 'SET_AUTH_LOGIN_FAIL',

    UPDATE_INFOR_USER_SUCCESS: 'UPDATE_INFOR_USER_SUCCESS',
    UPDATE_INFOR_USER_FAIL: 'UPDATE_INFOR_USER_FAIL',
    RESET_PROFILE: 'RESET_PROFILE',
}
export const sortTypes =  {
    SORT_DAY_INCREASED: 'SORT_DAY_INCREASED',
    SORT_DAY_DECREASED: 'SORT_DAY_DECREASED',
    SORT_VIEWS_INCREASED: 'SORT_VIEWS_INCREASED',
    SORT_VIEWS_DECREASED: 'SORT_VIEWS_DECREASED',
    SORT_SALES_INCREASED: 'SORT_SALES_INCREASED',
    SORT_SALES_DECREASED: 'SORT_SALES_DECREASED',
    SORT_PRICE_INCREASED: 'SORT_PRICE_INCREASED',
    SORT_PRICE_DECREASED: 'SORT_PRICE_DECREASED',

}
export const cartTypes = {
    SET_CART: 'SET_CART',
    SET_CITY: 'SET_CITY',
    SET_DICTRICT: 'SET_DISTRICT',
    SET_WARD: 'SET_WARD',
    PAYMENT_SUCCESS: 'PAYMENT_SUCCESS',
    PAYMENT_FAIL: 'PAYMENT_FAIL',
    RESET_PAYMENT: 'RESET_PAYMENT'
}
export const purchaseHistoryTypes = {
    SET_PURCHASED_HISTORY: 'SET_PURCHASED_HISTORY',
    
}